name = "main_world"

[[systems]]
name = "RestartSystem"
priority = 0
[[systems]]
name = "PauseSystem"
# priority = 1
# [[systems]]
# name = "PlayerInputSystem"
# priority = 2
# [[systems]]
# name = "GravitySystem"
# priority = 3
# [[systems]]
# name = "PhysicsSystem"
# priority = 4
# [[systems]]
# name = "CollisionSystem"
# priority = 5
# [[systems]]
# name = "CollisionResolverSystem"
# priority = 6
# [[systems]]
# name = "GameOverSystem"
# priority = 7
# [[systems]]
# name = "CameraSystem"
# priority = 8
# [[systems]]
# name = "ScoreSystem"
# priority = 9
# [[systems]]
# name = "LevelGenSystem"
# priority = 10

[[entities]]
name = "ActiveCamera"

[[entities]]
name = "Biog"
