name = "main_world"

[[systems]]
name = "PauseSystem"
priority = 0
# [[systems]]
# name = "PlayerSystem"
# priority = 1
[[systems]]
name = "GravitySystem"
priority = 2
[[systems]]
name = "PhysicsSystem"
priority = 3
[[systems]]
name = "CollisionSystem"
priority = 4
[[systems]]
name = "CollisionResolverSystem"
priority = 5
[[systems]]
name = "CameraSystem"
priority = 6
# [[systems]]
# name = "RestartSystem"
# priority = 7
[[systems]]
name = "LevelGenSystem"
priority = 8

[[entities]]
name = "ActiveCamera"
